version: "3"
services:
  database:
    image: postgres:12.15-bullseye
    container_name: auth-db
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - database-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - docker.env
    ports:
      - "9999:80"
    depends_on:
      - database
    networks:
      - database-network

  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - database-network

volumes:
  pg-data:

networks:
  database-network:
    driver: bridge